# Introduction to Data Analysis with Pandas

[Pandas](https://pandas.pydata.org/) ist eine Library und der de-facto Industry Standart für die Datenanalyse in Python. Installiere Pandas in deinem Environment mit `pip install pandas`.

## Daten importieren

Pandas kann eine vielzahl von Files öffnen, darunter `.csv`, `.excel` oder `.txt`.

In [2]:
# Pandas Library importieren
import pandas as pd
data = pd.read_excel("./data/african_countries_dataset.xlsx", sheet_name="Data")

In [3]:
# Verifiziere das der Import funktioniert hat
data.head()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.0,2381740.0,0.0,998,17.3,0.8,81.8,47022473.0,29.1,77.9,75.3,1.54,15200.0,11.81,30.8,87.4,75.3,71.0
1,Angola,ao,1246700.0,1246700.0,0.0,1600,36.8,52.5,10.6,37202061.0,16.3,62.9,68.7,3.33,7200.0,14.62,28.2,82.6,62.4,39.0
2,Benin,bn,112622.0,110622.0,2000.0,121,43.1,26.9,30.0,14697052.0,17.2,63.0,50.1,3.29,3700.0,1.45,3.9,56.9,35.0,34.0
3,Botswana,bc,581730.0,566730.0,15000.0,0,45.6,26.5,27.9,2450668.0,27.1,66.4,72.9,1.34,18800.0,23.38,45.4,88.0,88.9,77.0
4,Burkina Faso,uv,274200.0,273800.0,400.0,0,53.2,22.4,24.4,23042199.0,18.7,64.2,32.5,2.40,2500.0,5.29,8.0,54.5,37.8,20.0

## Datenstruktur verstehen

- Ein pandas DataFrame ist eine tabellenartige Datenstruktur in Python, die Daten in Zeilen und Spalten organisiert.
- Spalten-Namen ausgeben
- Ersten 5 Einträge ausgeben
- Einen spezifischen Eintrag an Index-Position `n` ausgeben
- Eine spezifische Spalte ausgeben

In [4]:
# What type does "data" have?
type(data)

pandas.core.frame.DataFrame

In [5]:
# Print the columns of the DataFrame
data.columns

Index(['Land', 'Country_Code', 'Fläche_Total_km2', 'Fläche_Land_km2',
       'Fläche_Wasser_km2', 'Küstenlänge_km', 'Landnutzung_Landwirtschaft_%',
       'Landnutzung_Wald_%', 'Landnutzung_Other_%', 'Bevölkerung',
       'Medianalter', 'Lebenserwartung', 'Urbanisierung_%',
       'Bevölkerungswachstum_%', 'BIP_pro_Kopf_USD', 'Arbeitslosigkeit_%',
       'Jugendarbeitslosigkeit_%', 'Alphabetisierung_M_%',
       'Alphabetisierung_F_%', 'Internetnutzer_%'],
      dtype='object')

In [6]:
# print the first 5 entries
data.head()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.0,2381740.0,0.0,998,17.3,0.8,81.8,47022473.0,29.1,77.9,75.3,1.54,15200.0,11.81,30.8,87.4,75.3,71.0
1,Angola,ao,1246700.0,1246700.0,0.0,1600,36.8,52.5,10.6,37202061.0,16.3,62.9,68.7,3.33,7200.0,14.62,28.2,82.6,62.4,39.0
2,Benin,bn,112622.0,110622.0,2000.0,121,43.1,26.9,30.0,14697052.0,17.2,63.0,50.1,3.29,3700.0,1.45,3.9,56.9,35.0,34.0
3,Botswana,bc,581730.0,566730.0,15000.0,0,45.6,26.5,27.9,2450668.0,27.1,66.4,72.9,1.34,18800.0,23.38,45.4,88.0,88.9,77.0
4,Burkina Faso,uv,274200.0,273800.0,400.0,0,53.2,22.4,24.4,23042199.0,18.7,64.2,32.5,2.40,2500.0,5.29,8.0,54.5,37.8,20.0

In [7]:
# print the first n entries
data.head(10)

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.0,0.0,998,17.3,0.8,81.8,47022473.0,29.1,77.9,75.3,1.54,15200.0,11.81,30.8,87.4,75.3,71.0
1,Angola,ao,1246700.000,1246700.0,0.0,1600,36.8,52.5,10.6,37202061.0,16.3,62.9,68.7,3.33,7200.0,14.62,28.2,82.6,62.4,39.0
2,Benin,bn,112622.000,110622.0,2000.0,121,43.1,26.9,30.0,14697052.0,17.2,63.0,50.1,3.29,3700.0,1.45,3.9,56.9,35.0,34.0
3,Botswana,bc,581730.000,566730.0,15000.0,0,45.6,26.5,27.9,2450668.0,27.1,66.4,72.9,1.34,18800.0,23.38,45.4,88.0,88.9,77.0
4,Burkina Faso,uv,274200.000,273800.0,400.0,0,53.2,22.4,24.4,23042199.0,18.7,64.2,32.5,2.40,2500.0,5.29,8.0,54.5,37.8,20.0
5,Burundi,by,27830.000,25680.0,2150.0,0,82.8,10.9,6.3,13590102.0,18.4,68.1,14.8,2.81,800.0,0.93,1.7,81.3,68.4,11.0
6,C&ocirc;te d'Ivoire,iv,322463.000,318003.0,4460.0,515,84.2,8.2,7.6,29981758.0,21.2,63.2,53.1,2.13,6500.0,2.40,4.0,93.1,86.7,38.0
7,Cabo Verde,cv,4033.000,4033.0,0.0,965,19.6,11.5,68.9,611014.0,28.8,74.3,68.0,1.16,9300.0,11.99,28.7,94.2,87.4,72.0
8,Cameroon,cm,475440.000,472710.0,2730.0,402,20.6,42.8,36.6,30966105.0,18.9,64.2,59.3,2.71,4900.0,3.65,6.4,82.6,71.6,44.0
9,Chad,cd,1.284,1259200.0,24800.0,0,40.0,3.2,56.8,19093595.0,16.7,60.0,24.4,3.01,1700.0,1.08,1.5,35.4,18.2,12.0

In [8]:
# print the last 5 entries
data.tail()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
51,Uganda,ug,241038.0,197100.0,43938.0,0,71.9,11.2,16.9,49283041.0,16.2,69.7,26.8,3.18,2800.0,2.83,4.5,84.0,74.3,10.0
52,Western Sahara,wi,NaN,266000.0,0.0,1110,18.8,2.7,78.5,NaN,21.8,64.5,86.8,2.54,NaN,NaN,NaN,NaN,NaN,NaN
53,Zambia,za,752618.0,743398.0,9220.0,0,32.1,59.8,8.2,20799116.0,18.4,66.9,46.3,2.83,3700.0,5.91,9.8,90.6,83.1,31.0
54,Zimbabwe,zi,390757.0,386847.0,3910.0,0,39.5,44.9,15.7,17150352.0,21.2,67.2,32.5,1.91,3400.0,8.76,14.3,88.3,90.9,33.0
55,Central African Republic,ct,622984.0,622984.0,0.0,0,9.0,35.7,55.3,5650957.0,20.4,56.4,43.6,1.76,1100.0,6.29,10.7,49.2,26.2,11.0

In [9]:
# print/access an item on a specific location, index starts at 0!
data.iloc[2]

Land                                 Benin
Country_Code                            bn
Fläche_Total_km2                  112622.0
Fläche_Land_km2                   110622.0
Fläche_Wasser_km2                   2000.0
Küstenlänge_km                         121
Landnutzung_Landwirtschaft_%          43.1
Landnutzung_Wald_%                    26.9
Landnutzung_Other_%                   30.0
Bevölkerung                     14697052.0
Medianalter                           17.2
Lebenserwartung                       63.0
Urbanisierung_%                       50.1
Bevölkerungswachstum_%                3.29
BIP_pro_Kopf_USD                    3700.0
Arbeitslosigkeit_%                    1.45
Jugendarbeitslosigkeit_%               3.9
Alphabetisierung_M_%                  56.9
Alphabetisierung_F_%                  35.0
Internetnutzer_%                      34.0
Name: 2, dtype: object

In [10]:
# print/access a specific column, also helpful to get index numbers
data["Land"]

0                      Algeria
1                       Angola
2                        Benin
3                     Botswana
4                 Burkina Faso
5                      Burundi
6          C&ocirc;te d'Ivoire
7                   Cabo Verde
8                     Cameroon
9                         Chad
10                     Comoros
11         Congo (Brazzaville)
12                         DRC
13                    Djibouti
14                       Egypt
15           Equatorial Guinea
16                     Eritrea
17                    Eswatini
18                    Ethiopia
19                       Gabon
20                       Ghana
21                      Guinea
22               Guinea-Bissau
23                       Kenya
24                     Lesotho
25                     Liberia
26                       Libya
27                  Madagascar
28                      Malawi
29                        Mali
30                  Mauritania
31                   Mauritius
32                     Morocco
33                  Mozambique
34                     Namibia
35                       Niger
36                     Nigeria
37                      Rwanda
38       Sao Tome and Principe
39                     Senegal
40                  Seychelles
41                Sierra Leone
42                     Somalia
43                South Africa
44                 South Sudan
45                       Sudan
46                 Switzerland
47                    Tanzania
48                  The Gambia
49                        Togo
50                     Tunisia
51                      Uganda
52              Western Sahara
53                      Zambia
54                    Zimbabwe
55    Central African Republic
Name: Land, dtype: object

In [11]:
# generate a subset based on the index number, e.g. all countries with letter C
# Python slices are start inclusive, end exclusive, so 6:12 gives you rows 6 through 11.
subset = data.iloc[6:12]
subset

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
6,C&ocirc;te d'Ivoire,iv,322463.000,318003.0,4460.0,515,84.2,8.2,7.6,29981758.0,21.2,63.2,53.1,2.13,6500.0,2.40,4.0,93.1,86.7,38.0
7,Cabo Verde,cv,4033.000,4033.0,0.0,965,19.6,11.5,68.9,611014.0,28.8,74.3,68.0,1.16,9300.0,11.99,28.7,94.2,87.4,72.0
8,Cameroon,cm,475440.000,472710.0,2730.0,402,20.6,42.8,36.6,30966105.0,18.9,64.2,59.3,2.71,4900.0,3.65,6.4,82.6,71.6,44.0
9,Chad,cd,1.284,1259200.0,24800.0,0,40.0,3.2,56.8,19093595.0,16.7,60.0,24.4,3.01,1700.0,1.08,1.5,35.4,18.2,12.0
10,Comoros,cn,2235.000,2235.0,0.0,340,71.5,17.2,11.3,900141.0,22.7,67.8,30.1,1.30,3500.0,5.80,10.9,67.0,56.9,27.0
11,Congo (Brazzaville),cf,342000.000,341500.0,500.0,169,31.3,64.2,4.5,6097665.0,20.7,72.9,69.2,2.38,6200.0,20.05,41.2,85.9,75.4,36.0

## Über Datenframe Iterieren

In [ ]:
# Über Columns iterieren
for col in data.columns:
    print(col)

Land
Country_Code
Fläche_Total_km2
Fläche_Land_km2
Fläche_Wasser_km2
Küstenlänge_km
Landnutzung_Landwirtschaft_%
Landnutzung_Wald_%
Landnutzung_Other_%
Bevölkerung
Medianalter
Lebenserwartung
Urbanisierung_%
Bevölkerungswachstum_%
BIP_pro_Kopf_USD
Arbeitslosigkeit_%
Jugendarbeitslosigkeit_%
Alphabetisierung_M_%
Alphabetisierung_F_%
Internetnutzer_%

In [36]:
# Über items iterieren
for idx, row in data.iterrows():
    print(idx, row)

0 Land                                Algeria
Country_Code                             ag
Fläche_Total_km2                2381740.000
Fläche_Land_km2                 2381740.000
Fläche_Wasser_km2                     0.000
Küstenlänge_km                          998
Landnutzung_Landwirtschaft_%         17.300
Landnutzung_Wald_%                    0.800
Landnutzung_Other_%                  81.800
Bevölkerung                    47022473.000
Medianalter                          29.100
Lebenserwartung                      77.900
Urbanisierung_%                      75.300
Bevölkerungswachstum_%                1.540
BIP_pro_Kopf_USD                  15200.000
Arbeitslosigkeit_%                   11.810
Jugendarbeitslosigkeit_%             30.800
Alphabetisierung_M_%                 87.400
Alphabetisierung_F_%                 75.300
Internetnutzer_%                     71.000
Name: 0, dtype: object
1 Land                                 Angola
Country_Code                             ao
Fläche_Total_km2                1246700.000
Fläche_Land_km2                 1246700.000
Fläche_Wasser_km2                     0.000
Küstenlänge_km                         1600
Landnutzung_Landwirtschaft_%         36.800
Landnutzung_Wald_%                   52.500
Landnutzung_Other_%                  10.600
Bevölkerung                    37202061.000
Medianalter                          16.300
Lebenserwartung                      62.900
Urbanisierung_%                      68.700
Bevölkerungswachstum_%                3.330
BIP_pro_Kopf_USD                   7200.000
Arbeitslosigkeit_%                   14.620
Jugendarbeitslosigkeit_%             28.200
Alphabetisierung_M_%                 82.600
Alphabetisierung_F_%                 62.400
Internetnutzer_%                     39.000
Name: 1, dtype: object
2 Land                                  Benin
Country_Code                             bn
Fläche_Total_km2                 112622.000
Fläche_Land_km2                  110622.000
Fläche_Wasser_km2                  2000.000
Küstenlänge_km                          121
Landnutzung_Landwirtschaft_%         43.100
Landnutzung_Wald_%                   26.900
Landnutzung_Other_%                  30.000
Bevölkerung                    14697052.000
Medianalter                          17.200
Lebenserwartung                      63.000
Urbanisierung_%                      50.100
Bevölkerungswachstum_%                3.290
BIP_pro_Kopf_USD                   3700.000
Arbeitslosigkeit_%                    1.450
Jugendarbeitslosigkeit_%              3.900
Alphabetisierung_M_%                 56.900
Alphabetisierung_F_%                 35.000
Internetnutzer_%                     34.000
Name: 2, dtype: object
3 Land                              Botswana
Country_Code                            bc
Fläche_Total_km2                581730.000
Fläche_Land_km2                 566730.000
Fläche_Wasser_km2                15000.000
Küstenlänge_km                           0
Landnutzung_Landwirtschaft_%        45.600
Landnutzung_Wald_%                  26.500
Landnutzung_Other_%                 27.900
Bevölkerung                    2450668.000
Medianalter                         27.100
Lebenserwartung                     66.400
Urbanisierung_%                     72.900
Bevölkerungswachstum_%               1.340
BIP_pro_Kopf_USD                 18800.000
Arbeitslosigkeit_%                  23.380
Jugendarbeitslosigkeit_%            45.400
Alphabetisierung_M_%                88.000
Alphabetisierung_F_%                88.900
Internetnutzer_%                    77.000
Name: 3, dtype: object
4 Land                            Burkina Faso
Country_Code                              uv
Fläche_Total_km2                  274200.000
Fläche_Land_km2                   273800.000
Fläche_Wasser_km2                    400.000
Küstenlänge_km                             0
Landnutzung_Landwirtschaft_%          53.200
Landnutzung_Wald_%                    22.400
Landnutzung_Other_%                   24.400
Bevölkerung                     23042199.000
Medianalter                           18.700
Lebenserwartung                       64.200
Urbanisierung_%                       32.500
Bevölkerungswachstum_%                 2.400
BIP_pro_Kopf_USD                    2500.000
Arbeitslosigkeit_%                     5.290
Jugendarbeitslosigkeit_%               8.000
Alphabetisierung_M_%                  54.500
Alphabetisierung_F_%                  37.800
Internetnutzer_%                      20.000
Name: 4, dtype: object
5 Land                                Burundi
Country_Code                             by
Fläche_Total_km2                  27830.000
Fläche_Land_km2                   25680.000
Fläche_Wasser_km2                  2150.000
Küstenlänge_km                            0
Landnutzung_Landwirtschaft_%         82.800
Landnutzung_Wald_%                   10.900
Landnutzung_Other_%                   6.300
Bevölkerung                    13590102.000
Medianalter                          18.400
Lebenserwartung                      68.100
Urbanisierung_%                      14.800
Bevölkerungswachstum_%                2.810
BIP_pro_Kopf_USD                    800.000
Arbeitslosigkeit_%                    0.930
Jugendarbeitslosigkeit_%              1.700
Alphabetisierung_M_%                 81.300
Alphabetisierung_F_%                 68.400
Internetnutzer_%                     11.000
Name: 5, dtype: object
6 Land                            C&ocirc;te d'Ivoire
Country_Code                                     iv
Fläche_Total_km2                         322463.000
Fläche_Land_km2                          318003.000
Fläche_Wasser_km2                          4460.000
Küstenlänge_km                                  515
Landnutzung_Landwirtschaft_%                 84.200
Landnutzung_Wald_%                            8.200
Landnutzung_Other_%                           7.600
Bevölkerung                            29981758.000
Medianalter                                  21.200
Lebenserwartung                              63.200
Urbanisierung_%                              53.100
Bevölkerungswachstum_%                        2.130
BIP_pro_Kopf_USD                           6500.000
Arbeitslosigkeit_%                            2.400
Jugendarbeitslosigkeit_%                      4.000
Alphabetisierung_M_%                         93.100
Alphabetisierung_F_%                         86.700
Internetnutzer_%                             38.000
Name: 6, dtype: object
7 Land                            Cabo Verde
Country_Code                            cv
Fläche_Total_km2                  4033.000
Fläche_Land_km2                   4033.000
Fläche_Wasser_km2                    0.000
Küstenlänge_km                         965
Landnutzung_Landwirtschaft_%        19.600
Landnutzung_Wald_%                  11.500
Landnutzung_Other_%                 68.900
Bevölkerung                     611014.000
Medianalter                         28.800
Lebenserwartung                     74.300
Urbanisierung_%                     68.000
Bevölkerungswachstum_%               1.160
BIP_pro_Kopf_USD                  9300.000
Arbeitslosigkeit_%                  11.990
Jugendarbeitslosigkeit_%            28.700
Alphabetisierung_M_%                94.200
Alphabetisierung_F_%                87.400
Internetnutzer_%                    72.000
Name: 7, dtype: object
8 Land                               Cameroon
Country_Code                             cm
Fläche_Total_km2                 475440.000
Fläche_Land_km2                  472710.000
Fläche_Wasser_km2                  2730.000
Küstenlänge_km                          402
Landnutzung_Landwirtschaft_%         20.600
Landnutzung_Wald_%                   42.800
Landnutzung_Other_%                  36.600
Bevölkerung                    30966105.000
Medianalter                          18.900
Lebenserwartung                      64.200
Urbanisierung_%                      59.300
Bevölkerungswachstum_%                2.710
BIP_pro_Kopf_USD                   4900.000
Arbeitslosigkeit_%                    3.650
Jugendarbeitslosigkeit_%              6.400
Alphabetisierung_M_%                 82.600
Alphabetisierung_F_%                 71.600
Internetnutzer_%                     44.000
Name: 8, dtype: object
9 Land                                   Chad
Country_Code                             cd
Fläche_Total_km2                      1.284
Fläche_Land_km2                 1259200.000
Fläche_Wasser_km2                 24800.000
Küstenlänge_km                            0
Landnutzung_Landwirtschaft_%         40.000
Landnutzung_Wald_%                    3.200
Landnutzung_Other_%                  56.800
Bevölkerung                    19093595.000
Medianalter                          16.700
Lebenserwartung                      60.000
Urbanisierung_%                      24.400
Bevölkerungswachstum_%                3.010
BIP_pro_Kopf_USD                   1700.000
Arbeitslosigkeit_%                    1.080
Jugendarbeitslosigkeit_%              1.500
Alphabetisierung_M_%                 35.400
Alphabetisierung_F_%                 18.200
Internetnutzer_%                     12.000
Name: 9, dtype: object
10 Land                              Comoros
Country_Code                           cn
Fläche_Total_km2                 2235.000
Fläche_Land_km2                  2235.000
Fläche_Wasser_km2                   0.000
Küstenlänge_km                        340
Landnutzung_Landwirtschaft_%       71.500
Landnutzung_Wald_%                 17.200
Landnutzung_Other_%                11.300
Bevölkerung                    900141.000
Medianalter                        22.700
Lebenserwartung                    67.800
Urbanisierung_%                    30.100
Bevölkerungswachstum_%              1.300
BIP_pro_Kopf_USD                 3500.000
Arbeitslosigkeit_%                  5.800
Jugendarbeitslosigkeit_%           10.900
Alphabetisierung_M_%               67.000
Alphabetisierung_F_%               56.900
Internetnutzer_%                   27.000
Name: 10, dtype: object
11 Land                            Congo (Brazzaville)
Country_Code                                     cf
Fläche_Total_km2                         342000.000
Fläche_Land_km2                          341500.000
Fläche_Wasser_km2                           500.000
Küstenlänge_km                                  169
Landnutzung_Landwirtschaft_%                 31.300
Landnutzung_Wald_%                           64.200
Landnutzung_Other_%                           4.500
Bevölkerung                             6097665.000
Medianalter                                  20.700
Lebenserwartung                              72.900
Urbanisierung_%                              69.200
Bevölkerungswachstum_%                        2.380
BIP_pro_Kopf_USD                           6200.000
Arbeitslosigkeit_%                           20.050
Jugendarbeitslosigkeit_%                     41.200
Alphabetisierung_M_%                         85.900
Alphabetisierung_F_%                         75.400
Internetnutzer_%                             36.000
Name: 11, dtype: object
12 Land                                     DRC
Country_Code                              cg
Fläche_Total_km2                 2344858.000
Fläche_Land_km2                  2267048.000
Fläche_Wasser_km2                  77810.000
Küstenlänge_km                            37
Landnutzung_Landwirtschaft_%          15.500
Landnutzung_Wald_%                    54.700
Landnutzung_Other_%                   29.800
Bevölkerung                    115403027.000
Medianalter                           16.900
Lebenserwartung                       62.600
Urbanisierung_%                       47.400
Bevölkerungswachstum_%                 3.110
BIP_pro_Kopf_USD                    1500.000
Arbeitslosigkeit_%                     4.540
Jugendarbeitslosigkeit_%               8.600
Alphabetisierung_M_%                  89.500
Alphabetisierung_F_%                  70.800
Internetnutzer_%                      27.000
Name: 12, dtype: object
13 Land                             Djibouti
Country_Code                           dj
Fläche_Total_km2                23200.000
Fläche_Land_km2                 23180.000
Fläche_Wasser_km2                  20.000
Küstenlänge_km                        314
Landnutzung_Landwirtschaft_%       73.500
Landnutzung_Wald_%                  0.300
Landnutzung_Other_%                26.200
Bevölkerung                    994974.000
Medianalter                        26.300
Lebenserwartung                    65.900
Urbanisierung_%                    78.600
Bevölkerungswachstum_%              1.890
BIP_pro_Kopf_USD                 6400.000
Arbeitslosigkeit_%                 26.260
Jugendarbeitslosigkeit_%           76.500
Alphabetisierung_M_%                  NaN
Alphabetisierung_F_%                  NaN
Internetnutzer_%                   65.000
Name: 13, dtype: object
14 Land                                   Egypt
Country_Code                              eg
Fläche_Total_km2                 1001450.000
Fläche_Land_km2                   995450.000
Fläche_Wasser_km2                   6000.000
Küstenlänge_km                          2450
Landnutzung_Landwirtschaft_%           4.100
Landnutzung_Wald_%                     0.000
Landnutzung_Other_%                   95.900
Bevölkerung                    111247248.000
Medianalter                           24.400
Lebenserwartung                       75.000
Urbanisierung_%                       43.100
Bevölkerungswachstum_%                 1.490
BIP_pro_Kopf_USD                   16700.000
Arbeitslosigkeit_%                     7.310
Jugendarbeitslosigkeit_%              19.000
Alphabetisierung_M_%                  78.800
Alphabetisierung_F_%                  67.400
Internetnutzer_%                      72.000
Name: 14, dtype: object
15 Land                            Equatorial Guinea
Country_Code                                   ek
Fläche_Total_km2                        28051.000
Fläche_Land_km2                         28051.000
Fläche_Wasser_km2                           0.000
Küstenlänge_km                                296
Landnutzung_Landwirtschaft_%                3.700
Landnutzung_Wald_%                         86.700
Landnutzung_Other_%                         9.600
Bevölkerung                           1795834.000
Medianalter                                22.100
Lebenserwartung                            63.900
Urbanisierung_%                            74.400
Bevölkerungswachstum_%                      3.230
BIP_pro_Kopf_USD                        15700.000
Arbeitslosigkeit_%                          8.670
Jugendarbeitslosigkeit_%                   16.400
Alphabetisierung_M_%                       97.400
Alphabetisierung_F_%                       93.000
Internetnutzer_%                           67.000
Name: 15, dtype: object
16 Land                               Eritrea
Country_Code                            er
Fläche_Total_km2                117600.000
Fläche_Land_km2                 101000.000
Fläche_Wasser_km2                16600.000
Küstenlänge_km                        2234
Landnutzung_Landwirtschaft_%        62.700
Landnutzung_Wald_%                   8.700
Landnutzung_Other_%                 28.600
Bevölkerung                    6343956.000
Medianalter                         21.300
Lebenserwartung                     67.500
Urbanisierung_%                     43.300
Bevölkerungswachstum_%               1.120
BIP_pro_Kopf_USD                       NaN
Arbeitslosigkeit_%                   5.870
Jugendarbeitslosigkeit_%            10.000
Alphabetisierung_M_%                84.400
Alphabetisierung_F_%                68.900
Internetnutzer_%                    27.000
Name: 16, dtype: object
17 Land                              Eswatini
Country_Code                            wz
Fläche_Total_km2                 17364.000
Fläche_Land_km2                  17204.000
Fläche_Wasser_km2                  160.000
Küstenlänge_km                           0
Landnutzung_Landwirtschaft_%        69.500
Landnutzung_Wald_%                  29.100
Landnutzung_Other_%                  1.500
Bevölkerung                    1138089.000
Medianalter                         24.600
Lebenserwartung                     60.700
Urbanisierung_%                     24.800
Bevölkerungswachstum_%               0.700
BIP_pro_Kopf_USD                 10100.000
Arbeitslosigkeit_%                  37.640
Jugendarbeitslosigkeit_%            65.000
Alphabetisierung_M_%                88.300
Alphabetisierung_F_%                88.500
Internetnutzer_%                    58.000
Name: 17, dtype: object
18 Land                                Ethiopia
Country_Code                              et
Fläche_Total_km2                 1104300.000
Fläche_Land_km2                  1096570.000
Fläche_Wasser_km2                   7730.000
Küstenlänge_km                             0
Landnutzung_Landwirtschaft_%          34.100
Landnutzung_Wald_%                    15.000
Landnutzung_Other_%                   50.900
Bevölkerung                    118550298.000
Medianalter                           20.400
Lebenserwartung                       67.700
Urbanisierung_%                       23.200
Bevölkerungswachstum_%                 2.370
BIP_pro_Kopf_USD                    2800.000
Arbeitslosigkeit_%                     3.500
Jugendarbeitslosigkeit_%               5.600
Alphabetisierung_M_%                  57.200
Alphabetisierung_F_%                  44.400
Internetnutzer_%                      19.000
Name: 18, dtype: object
19 Land                                 Gabon
Country_Code                            gb
Fläche_Total_km2                267667.000
Fläche_Land_km2                 257667.000
Fläche_Wasser_km2                10000.000
Küstenlänge_km                         885
Landnutzung_Landwirtschaft_%         8.400
Landnutzung_Wald_%                  91.200
Landnutzung_Other_%                  0.400
Bevölkerung                    2455105.000
Medianalter                         22.000
Lebenserwartung                     70.400
Urbanisierung_%                     91.000
Bevölkerungswachstum_%               2.370
BIP_pro_Kopf_USD                 18700.000
Arbeitslosigkeit_%                  20.360
Jugendarbeitslosigkeit_%            36.500
Alphabetisierung_M_%                86.200
Alphabetisierung_F_%                84.700
Internetnutzer_%                    74.000
Name: 19, dtype: object
20 Land                                  Ghana
Country_Code                             gh
Fläche_Total_km2                 238533.000
Fläche_Land_km2                  227533.000
Fläche_Wasser_km2                 11000.000
Küstenlänge_km                          539
Landnutzung_Landwirtschaft_%         55.400
Landnutzung_Wald_%                   35.200
Landnutzung_Other_%                   9.400
Bevölkerung                    34589092.000
Medianalter                          21.400
Lebenserwartung                      70.100
Urbanisierung_%                      59.200
Bevölkerungswachstum_%                2.150
BIP_pro_Kopf_USD                   6800.000
Arbeitslosigkeit_%                    3.080
Jugendarbeitslosigkeit_%              5.500
Alphabetisierung_M_%                 83.500
Alphabetisierung_F_%                 74.500
Internetnutzer_%                     70.000
Name: 20, dtype: object
21 Land                                 Guinea
Country_Code                             gv
Fläche_Total_km2                 245857.000
Fläche_Land_km2                  245717.000
Fläche_Wasser_km2                   140.000
Küstenlänge_km                          320
Landnutzung_Landwirtschaft_%         70.000
Landnutzung_Wald_%                   24.900
Landnutzung_Other_%                   5.200
Bevölkerung                    13986179.000
Medianalter                          19.400
Lebenserwartung                      64.600
Urbanisierung_%                      38.100
Bevölkerungswachstum_%                2.740

## Basic Statistics

Pandas bietet eine ganze Reihe von eingebauten Funktionen um einfache und komplexe Statistiken zu einem Datensatz auszugeben, darunter `.mean()`, `.median()`, `,mode()`, `.min()` und `.max()`.

- Der Mittelwert (Mean) ist der Durchschnitt, der berechnet wird, indem alle Werte addiert und durch die Anzahl der Werte geteilt werden. 
- Der Median hingegen ist der mittlere Wert in einer sortierten Datenreihe, der die Daten in zwei Hälften teilt – unabhängig von extremen Ausreißern. Sollte es sich um eine gerade Anzahl von Werten handeln so ist der Median das Mittel der beiden mittleren Werte. 
- Mode bezeichnet den häufigsten Wert in einer Zahlenreihe. Es kann auch mehrere Modalwerte geben wenn mehrere Zahlen gleich häufig vorkommen. 
- Min. und Max. bezeichnen den niedrigsten, bzw. höchsten Wert in einer sortierten oder unsortierten Zahlenreihe.

### Describe

Standardmäßig zeigt Pandas bei DataFrame.describe() sehr viele Nachkommastellen oder wissenschaftliche Notation (1.234567e+06) an. Das kann unübersichtlich wirken – besonders, wenn man die Zahlen nur überblicken und nicht hochpräzise weiterverarbeiten möchte. Über folgenden command kannst du alle Fließkommazahlen mit genau zwei Nachkommastellen anzeigen. Dadurch wird der Vergleich zwischen Spalten einfacher.

In [13]:
# .describe() outputs all popular statistics of a data set.
# Disable scientific notation for floats
pd.set_option('display.float_format', '{:.3f}'.format)
summary = data.describe()

summary

,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
count,55.000,55.000,55.000,56.000,56.000,56.000,56.000,55.000,56.000,56.000,56.000,56.000,53.000,54.000,55.000,52.000,52.000,55.000
mean,505573.210,534609.673,10466.600,734.750,46.345,26.762,26.893,27168755.345,22.359,67.323,49.363,2.113,8164.151,9.174,17.800,76.475,65.337,44.382
std,592731.876,592585.679,22013.958,1008.875,23.096,24.034,24.898,40180851.366,5.939,5.881,19.580,0.885,12231.251,8.026,16.875,16.011,22.087,23.808
min,1.267,455.000,0.000,0.000,3.400,0.000,0.100,98187.000,15.200,56.400,14.800,0.070,800.000,0.550,0.800,35.400,18.200,10.000
25%,33240.000,47191.000,70.000,0.000,31.900,9.150,7.600,3565850.000,19.050,63.150,35.350,1.478,2600.000,3.103,5.500,66.600,49.750,27.500
50%,267667.000,273800.000,2400.000,345.000,45.200,21.700,19.800,13623302.000,20.750,67.050,46.850,2.270,3900.000,5.890,10.700,81.950,69.850,36.000
75%,775999.000,854545.000,10660.000,973.250,68.300,41.825,39.100,32158529.500,23.075,70.650,65.825,2.590,9300.000,13.725,24.250,88.300,84.925,66.000
max,2381740.000,2381740.000,129813.000,4828.000,84.200,91.200,95.900,236747130.000,44.200,83.900,91.000,4.650,82600.000,37.640,76.500,97.400,96.400,97.000

### Mean, Median, Min. und Max.

In [14]:
# Calculate the mean
mean_arbeitslosigkeit = data['Arbeitslosigkeit_%'].mean()

# Calculate the median
median_arbeitslosigkeit = data['Arbeitslosigkeit_%'].median()

# Get the min
min_arbeitslosigkeit = data['Arbeitslosigkeit_%'].min()

# Get the max
max_arbeitslosigkeit = data['Arbeitslosigkeit_%'].max()

# Print the results
print(f"Mean Arbeitslosigkeit(%): {mean_arbeitslosigkeit}")
print(f"Median Arbeitslosigkeit(%): {median_arbeitslosigkeit}")
print(f"Min. Arbeitslosigkeit(%): {min_arbeitslosigkeit}")
print(f"Max. Arbeitslosigkeit(%): {max_arbeitslosigkeit}")

Mean Arbeitslosigkeit(%): 9.174444444444443
Median Arbeitslosigkeit(%): 5.890000000000001
Min. Arbeitslosigkeit(%): 0.55
Max. Arbeitslosigkeit(%): 37.64

In [15]:
# Get index of min and max
idx_min = data['Arbeitslosigkeit_%'].idxmin()
idx_max = data['Arbeitslosigkeit_%'].idxmax()

# Get full rows
row_min = data.loc[idx_min]
row_max = data.loc[idx_max]

# Do something with it
print("Row with min:", row_min["Land"])
print("Row with max:", row_max["Land"])

Row with min: Niger
Row with max: Eswatini

## Daten Sortieren

In [16]:
sorted_by_size = data.sort_values(by="Fläche_Total_km2", ascending=False)
sorted_by_size.head()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.000,0.000,998,17.300,0.800,81.800,47022473.000,29.100,77.900,75.300,1.540,15200.000,11.810,30.800,87.400,75.300,71.000
12,DRC,cg,2344858.000,2267048.000,77810.000,37,15.500,54.700,29.800,115403027.000,16.900,62.600,47.400,3.110,1500.000,4.540,8.600,89.500,70.800,27.000
45,Sudan,su,1861484.000,1731671.000,129813.000,853,60.300,9.600,30.000,50467278.000,19.300,67.800,36.300,2.550,2500.000,11.450,18.200,65.400,56.100,29.000
26,Libya,ly,1759540.000,1759540.000,0.000,1770,8.700,0.100,91.200,7361263.000,26.200,77.700,81.600,1.440,12500.000,18.740,49.400,96.700,85.600,88.000
1,Angola,ao,1246700.000,1246700.000,0.000,1600,36.800,52.500,10.600,37202061.000,16.300,62.900,68.700,3.330,7200.000,14.620,28.200,82.600,62.400,39.000

## Daten Filtern & Subsets erstellen

### Random Sample

In [17]:
# generate a random sample of countries
random_subset = data.sample(n=5, random_state=42)
random_subset

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.000,0.000,998,17.300,0.800,81.800,47022473.000,29.100,77.900,75.300,1.540,15200.000,11.810,30.800,87.400,75.300,71.000
5,Burundi,by,27830.000,25680.000,2150.000,0,82.800,10.900,6.300,13590102.000,18.400,68.100,14.800,2.810,800.000,0.930,1.700,81.300,68.400,11.000
33,Mozambique,mz,799380.000,786380.000,13000.000,2470,52.700,46.100,1.200,33350954.000,17.300,58.300,38.800,2.540,1500.000,3.540,7.600,74.100,53.800,21.000
13,Djibouti,dj,23200.000,23180.000,20.000,314,73.500,0.300,26.200,994974.000,26.300,65.900,78.600,1.890,6400.000,26.260,76.500,NaN,NaN,65.000
19,Gabon,gb,267667.000,257667.000,10000.000,885,8.400,91.200,0.400,2455105.000,22.000,70.400,91.000,2.370,18700.000,20.360,36.500,86.200,84.700,74.000

### Filtern nach Werten

Um einen Pandas Dataframe zu Filtern wird die Bedingung direkt in die eckigen Klammern geschrieben und das Resultat einer neuen Variable zugewiesen.

In [18]:
# filtering for an absolute value
landlocked_countries = data[data["Küstenlänge_km"] == 0]
landlocked_countries.head()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
3,Botswana,bc,581730.000,566730.000,15000.000,0,45.600,26.500,27.900,2450668.000,27.100,66.400,72.900,1.340,18800.000,23.380,45.400,88.000,88.900,77.000
4,Burkina Faso,uv,274200.000,273800.000,400.000,0,53.200,22.400,24.400,23042199.000,18.700,64.200,32.500,2.400,2500.000,5.290,8.000,54.500,37.800,20.000
5,Burundi,by,27830.000,25680.000,2150.000,0,82.800,10.900,6.300,13590102.000,18.400,68.100,14.800,2.810,800.000,0.930,1.700,81.300,68.400,11.000
9,Chad,cd,1.284,1259200.000,24800.000,0,40.000,3.200,56.800,19093595.000,16.700,60.000,24.400,3.010,1700.000,1.080,1.500,35.400,18.200,12.000
17,Eswatini,wz,17364.000,17204.000,160.000,0,69.500,29.100,1.500,1138089.000,24.600,60.700,24.800,0.700,10100.000,37.640,65.000,88.300,88.500,58.000

In [19]:
# filtering above or below a certain value
live_expectency_mean = data["Lebenserwartung"].mean()
print("Durschnittliche Lebenserwartung: ", live_expectency_mean)

live_expectency_above_avg = data[data["Lebenserwartung"] > live_expectency_mean]
live_expectency_above_avg.head()

Durschnittliche Lebenserwartung:  67.32321428571429

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.000,0.000,998,17.300,0.800,81.800,47022473.000,29.100,77.900,75.300,1.540,15200.000,11.810,30.800,87.400,75.300,71.000
5,Burundi,by,27830.000,25680.000,2150.000,0,82.800,10.900,6.300,13590102.000,18.400,68.100,14.800,2.810,800.000,0.930,1.700,81.300,68.400,11.000
7,Cabo Verde,cv,4033.000,4033.000,0.000,965,19.600,11.500,68.900,611014.000,28.800,74.300,68.000,1.160,9300.000,11.990,28.700,94.200,87.400,72.000
10,Comoros,cn,2235.000,2235.000,0.000,340,71.500,17.200,11.300,900141.000,22.700,67.800,30.100,1.300,3500.000,5.800,10.900,67.000,56.900,27.000
11,Congo (Brazzaville),cf,342000.000,341500.000,500.000,169,31.300,64.200,4.500,6097665.000,20.700,72.900,69.200,2.380,6200.000,20.050,41.200,85.900,75.400,36.000

In [20]:
# filtering within a range, e.g. based on quantiles
q1 = data['Lebenserwartung'].quantile(0.25)
q3 = data['Lebenserwartung'].quantile(0.75)

central_half = data[(data["Lebenserwartung"] > q1) & (data["Lebenserwartung"] < q3)]
central_half.head()

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
3,Botswana,bc,581730.000,566730.000,15000.000,0,45.600,26.500,27.900,2450668.000,27.100,66.400,72.900,1.340,18800.000,23.380,45.400,88.000,88.900,77.000
4,Burkina Faso,uv,274200.000,273800.000,400.000,0,53.200,22.400,24.400,23042199.000,18.700,64.200,32.500,2.400,2500.000,5.290,8.000,54.500,37.800,20.000
5,Burundi,by,27830.000,25680.000,2150.000,0,82.800,10.900,6.300,13590102.000,18.400,68.100,14.800,2.810,800.000,0.930,1.700,81.300,68.400,11.000
6,C&ocirc;te d'Ivoire,iv,322463.000,318003.000,4460.000,515,84.200,8.200,7.600,29981758.000,21.200,63.200,53.100,2.130,6500.000,2.400,4.000,93.100,86.700,38.000
8,Cameroon,cm,475440.000,472710.000,2730.000,402,20.600,42.800,36.600,30966105.000,18.900,64.200,59.300,2.710,4900.000,3.650,6.400,82.600,71.600,44.000

### Zwischenaufgabe

Schau dir alle Länder in der Excel Liste an: Ein Land wird dir auffallen da es nicht zu Afrika gehört. Füge in der unteren Zelle Code hinzu welcher dieses Land aus dem Datensatz herausfiltert so das du nachher einen Datensatz mit ausschliesslich afrikanischen Ländern hast.

In [21]:
# deine Lösung:

### Filtern von Zeilen mit Fehlenden Daten

In [22]:
# to drop all rows were some data is missing
print("Original length: ", len(data))

complete_set = data.dropna()
print("Complete Rows: ", len(complete_set))

Original length:  56
Complete Rows:  49

In [23]:
# it is also possible to get all rows with missing values
# isna() → True/False for each cell
# .any(axis=1) → True if any column in that row is missing
incomplete_set = data[data.isna().any(axis=1)]
incomplete_set

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
13,Djibouti,dj,23200.000,23180.000,20.000,314,73.500,0.300,26.200,994974.000,26.300,65.900,78.600,1.890,6400.000,26.260,76.500,NaN,NaN,65.000
16,Eritrea,er,117600.000,101000.000,16600.000,2234,62.700,8.700,28.600,6343956.000,21.300,67.500,43.300,1.120,NaN,5.870,10.000,84.400,68.900,27.000
40,Seychelles,se,455.000,455.000,0.000,491,3.400,73.300,23.400,98187.000,38.700,76.600,58.800,0.560,29500.000,NaN,16.500,95.400,96.400,87.000
42,Somalia,so,637657.000,627337.000,10320.000,3025,70.300,9.300,20.400,13017273.000,19.100,56.500,47.900,2.550,1400.000,19.030,34.300,NaN,NaN,28.000
44,South Sudan,od,644329.000,NaN,NaN,0,44.700,11.300,44.000,12703714.000,18.700,60.300,21.200,4.650,NaN,12.270,18.300,40.300,28.900,12.000
46,Switzerland,sz,41277.000,39997.000,1280.000,0,37.900,32.300,29.800,8860574.000,44.200,83.900,74.200,0.750,82600.000,4.050,8.000,NaN,NaN,97.000
52,Western Sahara,wi,NaN,266000.000,0.000,1110,18.800,2.700,78.500,NaN,21.800,64.500,86.800,2.540,NaN,NaN,NaN,NaN,NaN,NaN

### Filtern nach Liste

In [24]:
# select a subset of countries based on their names
north_africa = [
    "Algeria",
    "Egypt",
    "Libya",
    "Mauritania",
    "Morocco",
    "Sudan",
    "Tunisia",
    "Western Sahara"
]

na_subset = data[data["Land"].isin(north_africa)]
na_subset

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.000,0.000,998,17.300,0.800,81.800,47022473.000,29.100,77.900,75.300,1.540,15200.000,11.810,30.800,87.400,75.300,71.000
14,Egypt,eg,1001450.000,995450.000,6000.000,2450,4.100,0.000,95.900,111247248.000,24.400,75.000,43.100,1.490,16700.000,7.310,19.000,78.800,67.400,72.000
26,Libya,ly,1759540.000,1759540.000,0.000,1770,8.700,0.100,91.200,7361263.000,26.200,77.700,81.600,1.440,12500.000,18.740,49.400,96.700,85.600,88.000
30,Mauritania,mr,1030700.000,1030700.000,0.000,754,38.500,0.300,61.200,4328040.000,22.100,65.900,57.700,1.920,6300.000,10.510,23.700,71.800,62.200,44.000
32,Morocco,mo,716550.000,716300.000,250.000,2945,67.900,12.900,19.200,37387585.000,30.600,74.200,65.100,0.840,8900.000,9.110,22.600,84.800,67.400,90.000
45,Sudan,su,1861484.000,1731671.000,129813.000,853,60.300,9.600,30.000,50467278.000,19.300,67.800,36.300,2.550,2500.000,11.450,18.200,65.400,56.100,29.000
50,Tunisia,ts,163610.000,155360.000,8250.000,1148,62.400,4.500,33.000,12048847.000,34.400,77.300,70.500,0.580,12600.000,15.110,37.500,89.100,82.700,74.000
52,Western Sahara,wi,NaN,266000.000,0.000,1110,18.800,2.700,78.500,NaN,21.800,64.500,86.800,2.540,NaN,NaN,NaN,NaN,NaN,NaN

### Filtern von Spalten

In [25]:
# select only certain columns
col_selection = ["Land", "Fläche_Total_km2", "Landnutzung_Landwirtschaft_%", "Landnutzung_Wald_%"]
col_subset = data[col_selection]

col_subset.head()

,Land,Fläche_Total_km2,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%
0,Algeria,2381740.000,17.300,0.800
1,Angola,1246700.000,36.800,52.500
2,Benin,112622.000,43.100,26.900
3,Botswana,581730.000,45.600,26.500
4,Burkina Faso,274200.000,53.200,22.400

## Data Views vs. Copies 🔮

In Pandas passiert oft etwas Unerwartetes: Wenn du bspw. schreibst `na_subset = data[data["Land"].isin(north_africa)]`. Hier wird kein neuer Datensatz erstellt, sondern nur ein neuer Name für einen Ausschnitt (View) des Datensatzes vergeben. **Das heißt: Änderst du etwas in `na_subset`, siehst du die Änderung auch in `data` (und umgekehrt).

Wenn du wirklich unabhängig weiterarbeiten willst, musst du eine echte Kopie machen:

In [26]:
north_africa = [
    "Algeria",
    "Egypt",
    "Libya",
    "Mauritania",
    "Morocco",
    "Sudan",
    "Tunisia",
    "Western Sahara"
]

true_na_subset = data[data["Land"].isin(north_africa)].copy()
true_na_subset

,Land,Country_Code,Fläche_Total_km2,Fläche_Land_km2,Fläche_Wasser_km2,Küstenlänge_km,Landnutzung_Landwirtschaft_%,Landnutzung_Wald_%,Landnutzung_Other_%,Bevölkerung,Medianalter,Lebenserwartung,Urbanisierung_%,Bevölkerungswachstum_%,BIP_pro_Kopf_USD,Arbeitslosigkeit_%,Jugendarbeitslosigkeit_%,Alphabetisierung_M_%,Alphabetisierung_F_%,Internetnutzer_%
0,Algeria,ag,2381740.000,2381740.000,0.000,998,17.300,0.800,81.800,47022473.000,29.100,77.900,75.300,1.540,15200.000,11.810,30.800,87.400,75.300,71.000
14,Egypt,eg,1001450.000,995450.000,6000.000,2450,4.100,0.000,95.900,111247248.000,24.400,75.000,43.100,1.490,16700.000,7.310,19.000,78.800,67.400,72.000
26,Libya,ly,1759540.000,1759540.000,0.000,1770,8.700,0.100,91.200,7361263.000,26.200,77.700,81.600,1.440,12500.000,18.740,49.400,96.700,85.600,88.000
30,Mauritania,mr,1030700.000,1030700.000,0.000,754,38.500,0.300,61.200,4328040.000,22.100,65.900,57.700,1.920,6300.000,10.510,23.700,71.800,62.200,44.000
32,Morocco,mo,716550.000,716300.000,250.000,2945,67.900,12.900,19.200,37387585.000,30.600,74.200,65.100,0.840,8900.000,9.110,22.600,84.800,67.400,90.000
45,Sudan,su,1861484.000,1731671.000,129813.000,853,60.300,9.600,30.000,50467278.000,19.300,67.800,36.300,2.550,2500.000,11.450,18.200,65.400,56.100,29.000
50,Tunisia,ts,163610.000,155360.000,8250.000,1148,62.400,4.500,33.000,12048847.000,34.400,77.300,70.500,0.580,12600.000,15.110,37.500,89.100,82.700,74.000
52,Western Sahara,wi,NaN,266000.000,0.000,1110,18.800,2.700,78.500,NaN,21.800,64.500,86.800,2.540,NaN,NaN,NaN,NaN,NaN,NaN

## Export

In [27]:
na_subset.to_excel('./export/na_subset.xlsx', index=False)